import { NewsArticle, WeatherCity, OpinionPoll } from "./types";

export const mockArticles: NewsArticle[] = [
  {
    id: "news-1",
    title: "पुणे मेट्रोच्या तिसऱ्या टप्प्याचे काम अंतिम टप्प्यात; हिंजवडी ते शिवाजीनगर मार्गिका लवकरच खुली होणार",
    excerpt: "पुण्यातील आयटी हब मानल्या जाणाऱ्या हिंजवडीला शिवाजीनगरशी जोडणाऱ्या मेट्रो मार्गिकेचे काम वेगाने सुरू आहे. यामुळे हजारो आयटी कर्मचाऱ्यांचा प्रवास सुकर होणार आहे.",
    fullText: "पुणे महानगर प्रदेश विकास प्राधिकरण (PMRDA) च्या वतीने हिंजवडी ते शिवाजीनगर या तिसऱ्या मार्गिकेचे काम अंतिम टप्प्यात आले आहे.",
    category: "महाराष्ट्र",
    imageUrl: "https://images.unsplash.com/photo-1541417904950-b855846fe074?auto=format&fit=crop&w=800&q=80",
    date: "०८ जून २०२६",
    source: "Sandeep Shirguppe",
    views: 1240,
    likes: 85,
    commentsCount: 14,
    shares: 45,
    createdAt: Date.now() - 2 * 60 * 60 * 1000,
    trendingScore: 100,
    authorId: "contributor-1",
    authorHandle: "sandeep_news"
  },
  {
    id: "news-2",
    title: "राज्यातील नवीन राजकीय समीकरण: पुढील निवडणुकांची रणनीती",
    excerpt: "राज्यातील अनेक जिल्ह्यांमध्ये नवीन राजकीय समीकरणाची चर्चा सुरू असून, यामुळे सर्वच पक्षांची लगबग वाढली आहे. आगामी निवडणुका लवकरच होण्याची शक्यता आहे.",
    fullText: "राज्यातील राजकीय समीकरणे वेगाने बदलत असून, पुढील निवडणुकांच्या दृष्टीने सर्वच पक्षांनी मोर्चेबांधणीला सुरुवात केली आहे.",
    category: "राजकारण",
    imageUrl: "https://images.unsplash.com/photo-1599839619722-39751411ea63?auto=format&fit=crop&w=800&q=80",
    date: "०७ जून २०२६",
    source: "Rahul Deshmukh",
    views: 950,
    likes: 120,
    commentsCount: 8,
    shares: 20,
    createdAt: Date.now() - 24 * 60 * 60 * 1000,
    trendingScore: 90,
    authorId: "contributor-3",
    authorHandle: "rahul_tech"
  },
  {
    id: "news-3",
    title: "महाराष्ट्राचा वैभवशाली इतिहास: नवीन संशोधनातून उलगडले अनवट पैलू",
    excerpt: "नवीन ऐतिहासिक संशोधनातून महाराष्ट्राच्या वैभवशाली इतिहासाचे काही अनवट पैलू समोर आले आहेत. जुन्या कागदपत्रांच्या अभ्यासातून महत्त्वाची माहिती मिळाली आहे.",
    fullText: "अलीकडेच झालेल्या ऐतिहासिक संशोधनातून महाराष्ट्राच्या इतिहासातील अनेक नवनवीन गोष्टी उजेडात आल्या आहेत.",
    category: "इतिहास",
    imageUrl: "https://images.unsplash.com/photo-1540747913346-19e32fc3e620?auto=format&fit=crop&w=800&q=80",
    date: "०७ जून २०२६",
    source: "Payal Naik",
    views: 2100,
    likes: 450,
    commentsCount: 32,
    shares: 115,
    createdAt: Date.now() - 48 * 60 * 60 * 1000,
    trendingScore: 80,
    authorId: "contributor-2",
    authorHandle: "payal_ent"
  },
  {
    id: "news-4",
    title: "मान्सूनपूर्व पावसाची हजेरी; शेतकऱ्यांमध्ये समाधानाचे वातावरण",
    excerpt: "राज्याच्या अनेक भागांत मान्सूनपूर्व पावसाने हजेरी लावली असून, शेतकऱ्यांनी पेरणीपूर्व मशागतीच्या कामांना वेग दिला आहे.",
    fullText: "राज्याच्या अनेक भागांत मान्सूनपूर्व पावसाने हजेरी लावली आहे.",
    category: "महाराष्ट्र",
    imageUrl: "https://images.unsplash.com/photo-1620200423727-8127f75d7f53?auto=format&fit=crop&w=800&q=80",
    date: "०६ जून २०२६",
    source: "Sandeep Shirguppe",
    views: 680,
    likes: 54,
    commentsCount: 5,
    shares: 12,
    createdAt: Date.now() - 72 * 60 * 60 * 1000,
    trendingScore: 70,
    authorId: "contributor-1",
    authorHandle: "sandeep_news"
  },
  {
    id: "news-5",
    title: "सेंसेक्स आणि निफ्टीमध्ये मोठी उसळी, गुंतवणूकदारांना दिलासा",
    excerpt: "आजच्या सत्रात सेंसेक्स आणि निफ्टीने मोठी झेप घेतली असून गुंतवणूकदारांमध्ये आनंदाचे वातावरण आहे.",
    fullText: "आजच्या सत्रात सेंसेक्स आणि निफ्टीने मोठी झेप घेतली.",
    category: "राष्ट्रीय",
    imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&q=80",
    date: "०६ जून २०२६",
    source: "Rahul Deshmukh",
    views: 1500,
    likes: 200,
    commentsCount: 18,
    shares: 60,
    createdAt: Date.now() - 80 * 60 * 60 * 1000,
    trendingScore: 60,
    authorId: "contributor-3",
    authorHandle: "rahul_tech"
  },
  {
    id: "news-6",
    title: "मराठी चित्रपटसृष्टीत नव्या पर्वाची सुरुवात, तरुण दिग्दर्शकांची चमक",
    excerpt: "यंदाच्या वर्षात मराठी चित्रपटसृष्टीत अनेक नवोदित दिग्दर्शकांनी आपल्या कलाकृतींनी प्रेक्षकांची मने जिंकली आहेत.",
    fullText: "यंदाच्या वर्षात मराठी चित्रपटसृष्टीत अनेक नवोदित दिग्दर्शकांनी आपल्या कलाकृतींनी प्रेक्षकांची मने जिंकली आहेत.",
    category: "मनोरंजन",
    imageUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80",
    date: "०५ जून २०२६",
    source: "Payal Naik",
    views: 3200,
    likes: 610,
    commentsCount: 44,
    shares: 150,
    createdAt: Date.now() - 100 * 60 * 60 * 1000,
    trendingScore: 50,
    authorId: "contributor-2",
    authorHandle: "payal_ent"
  },
  {
    id: "news-7",
    title: "संपादकीय: पारदर्शक पत्रकारितेची गरज आणि आव्हाने",
    excerpt: "आजच्या माहिती युगात पारदर्शक आणि सत्यशोधक पत्रकारिता किती महत्त्वाची आहे यावर एक सखोल दृष्टिक्षेप.",
    fullText: "आजच्या माहिती युगात पारदर्शक आणि सत्यशोधक पत्रकारिता किती महत्त्वाची आहे यावर एक सखोल दृष्टिक्षेप.",
    category: "संपादकीय",
    imageUrl: "https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=800&q=80",
    date: "०४ जून २०२६",
    source: "Sandeep Shirguppe",
    views: 890,
    likes: 76,
    commentsCount: 9,
    shares: 22,
    createdAt: Date.now() - 120 * 60 * 60 * 1000,
    trendingScore: 40,
    authorId: "contributor-1",
    authorHandle: "sandeep_news"
  },
  {
    id: "news-8",
    title: "दहावी-बारावीच्या पुरवणी परीक्षांच्या तारखा जाहीर",
    excerpt: "राज्य मंडळाने दहावी आणि बारावीच्या पुरवणी परीक्षांचे वेळापत्रक जाहीर केले असून विद्यार्थ्यांनी अर्ज भरण्याचे आवाहन करण्यात आले आहे.",
    fullText: "राज्य मंडळाने दहावी आणि बारावीच्या पुरवणी परीक्षांचे वेळापत्रक जाहीर केले आहे.",
    category: "महाराष्ट्र",
    imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80",
    date: "०३ जून २०२६",
    source: "Rahul Deshmukh",
    views: 1100,
    likes: 65,
    commentsCount: 6,
    shares: 18,
    createdAt: Date.now() - 140 * 60 * 60 * 1000,
    trendingScore: 30,
    authorId: "contributor-3",
    authorHandle: "rahul_tech"
  }
];

export const mockWeather: WeatherCity[] = [
  { id: "w1", city: "मुंबई", temp: 31, condition: "अंशतः ढगाळ", icon: "🌤" },
  { id: "w2", city: "पुणे", temp: 28, condition: "ढगाळ", icon: "☁" },
  { id: "w3", city: "नागपूर", temp: 41, condition: "निरभ्र", icon: "☀" },
  { id: "w4", city: "च. संभाजीनगर", temp: 34, condition: "पावसाळी", icon: "🌦" }
];

export const mockPoll: OpinionPoll = {
  id: "poll-1",
  question: "राज्यातील रस्त्यांच्या सद्यस्थितीबाबत तुमचे मत काय आहे?",
  options: [
    { id: "opt-1", text: "समाधानकारक", votes: 128 },
    { id: "opt-2", text: "असमाधानकारक", votes: 342 }
  ],
  createdAt: Date.now(),
  isActive: true
};
